version: "3.8"

services:
  wait:
    build:
      context: .
    depends_on:
      app:
        condition: service_healthy

  app:
    image: 'woven-videoserver-plain:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "echo", "Done"]
      interval: 20s
      timeout: 10s
      retries: 3


  db:
    image: 'postgres:15-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - 5432
