version: "3.8"

services:
  videoserver:
    image: 'woven-videoserver-plain:latest'
    build:
      context: .
    container_name: videoserver
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '1996:1996'
    healthcheck:
      test: [ "CMD" ,"curl", "-f","http://localhost:1996/v1/health" ]
      interval: 5s
      retries: 10
      start_period: 5s
      timeout: 10s

  db:
    image: 'postgres:15-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - '5432:5432'

  proxy_server:
    image: haproxy:2.7-alpine
    depends_on:
      videoserver:
        condition: service_healthy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "8080:8080"
